using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace SkinPacker;

static class KeyStore
{
    public enum Status
    {
        Ready,
        Created,
        Mismatch
    }

    public static Status Load(out RSA rsa, out string message)
    {
        rsa = null;
        message = "";
        string root = FindProjectRoot();
        string keyPath = root == null
            ? Path.Combine(AppContext.BaseDirectory, "keys", "private-key.json")
            : Path.Combine(root, "Tools", "SkinPacker", "keys", "private-key.json");

        Directory.CreateDirectory(Path.GetDirectoryName(keyPath));

        if (!File.Exists(keyPath))
        {
            rsa = RSA.Create(2048);
            WritePrivateKey(keyPath, rsa.ExportParameters(true));
            if (root == null)
            {
                message = "Created a private key next to SkinPacker, but the Unity project was not found, so the public key was not written into the game.";
                return Status.Created;
            }

            WritePublicKeySource(root, rsa.ExportParameters(false));
            message = "Created a new signing key. Back up Tools/SkinPacker/keys. If that folder is lost, existing builds cannot accept new skins. Build the game once in Unity so this public key is inside the exe.";
            return Status.Created;
        }

        rsa = RSA.Create();
        rsa.ImportParameters(ReadPrivateKey(keyPath));
        if (root == null)
            return Status.Ready;

        string sourcePath = PublicKeyPath(root);
        string current = File.Exists(sourcePath) ? File.ReadAllText(sourcePath) : "";
        string modulus = Convert.ToBase64String(rsa.ExportParameters(false).Modulus);
        if (current.Contains("// modulus: " + modulus, StringComparison.Ordinal))
            return Status.Ready;

        if (current.Contains("// modulus: PLACEHOLDER", StringComparison.Ordinal) || !current.Contains("// modulus: ", StringComparison.Ordinal))
        {
            WritePublicKeySource(root, rsa.ExportParameters(false));
            message = "Wrote the public key into the game. Build the player once in Unity before shipping a client build.";
            return Status.Created;
        }

        message = "The private key does not match the public key already in the game. Restore Tools/SkinPacker/keys from the backup that belongs to this project. A new key was not created.";
        return Status.Mismatch;
    }

    public static string FindProjectRoot()
    {
        foreach (string start in new[] { AppContext.BaseDirectory, Directory.GetCurrentDirectory() })
        {
            var dir = new DirectoryInfo(start);
            while (dir != null)
            {
                bool hasProject = File.Exists(Path.Combine(dir.FullName, "ProjectSettings", "ProjectVersion.txt"));
                bool hasAssets = Directory.Exists(Path.Combine(dir.FullName, "Assets"));
                if (hasProject && hasAssets)
                    return dir.FullName;
                dir = dir.Parent;
            }
        }
        return null;
    }

    static string PublicKeyPath(string root)
    {
        return Path.Combine(root, "Assets", "Scripts", "Skin", "SkinPublicKey.cs");
    }

    static void WritePrivateKey(string path, RSAParameters key)
    {
        var file = new KeyFile
        {
            Modulus = Convert.ToBase64String(key.Modulus),
            Exponent = Convert.ToBase64String(key.Exponent),
            D = Convert.ToBase64String(key.D),
            P = Convert.ToBase64String(key.P),
            Q = Convert.ToBase64String(key.Q),
            DP = Convert.ToBase64String(key.DP),
            DQ = Convert.ToBase64String(key.DQ),
            InverseQ = Convert.ToBase64String(key.InverseQ)
        };
        string json = JsonSerializer.Serialize(file, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(path, json, new UTF8Encoding(false));
    }

    static RSAParameters ReadPrivateKey(string path)
    {
        var file = JsonSerializer.Deserialize<KeyFile>(File.ReadAllText(path));
        return new RSAParameters
        {
            Modulus = Convert.FromBase64String(file.Modulus),
            Exponent = Convert.FromBase64String(file.Exponent),
            D = Convert.FromBase64String(file.D),
            P = Convert.FromBase64String(file.P),
            Q = Convert.FromBase64String(file.Q),
            DP = Convert.FromBase64String(file.DP),
            DQ = Convert.FromBase64String(file.DQ),
            InverseQ = Convert.FromBase64String(file.InverseQ)
        };
    }

    public static void WritePublicKeySource(string root, RSAParameters key)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// Generated by Tools/SkinPacker. Do not edit.");
        builder.Append("// modulus: ").AppendLine(Convert.ToBase64String(key.Modulus));
        builder.AppendLine("public static class SkinPublicKey");
        builder.AppendLine("{");
        builder.AppendLine("    public static readonly byte[] Modulus = new byte[]");
        builder.AppendLine("    {");
        AppendBytes(builder, key.Modulus);
        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    public static readonly byte[] Exponent = new byte[]");
        builder.AppendLine("    {");
        AppendBytes(builder, key.Exponent);
        builder.AppendLine("    };");
        builder.AppendLine("}");
        Directory.CreateDirectory(Path.GetDirectoryName(PublicKeyPath(root)));
        File.WriteAllText(PublicKeyPath(root), builder.ToString(), new UTF8Encoding(false));
    }

    static void AppendBytes(StringBuilder builder, byte[] bytes)
    {
        for (int i = 0; i < bytes.Length; i++)
        {
            if (i % 16 == 0)
                builder.Append("        ");
            builder.Append(bytes[i]);
            if (i != bytes.Length - 1)
                builder.Append(", ");
            if (i % 16 == 15 || i == bytes.Length - 1)
                builder.AppendLine();
        }
    }

    sealed class KeyFile
    {
        public string Modulus { get; set; }
        public string Exponent { get; set; }
        public string D { get; set; }
        public string P { get; set; }
        public string Q { get; set; }
        public string DP { get; set; }
        public string DQ { get; set; }
        public string InverseQ { get; set; }
    }
}
